apiVersion: v1
kind: Service 
metadata: 
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
spec: 
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 8080  #port at which service is internally available
      targetPort: 8080 #port of container
      name: http
  type: ClusterIP  #only accessible inside the cluster